services:
  db:
    image: postgres:15
    container_name: postgres_tp1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app_tp1
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./sql:/app/sql
      - ./data:/app/data
      - ./out:/app/out
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ecommerce
      DB_USER: postgres
      DB_PASS: postgres
    command: tail -f /dev/null

volumes:
  db_data:
